sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t jadslim313/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jadslim313/docker-react npm run test